spring:
  application:
    name: http-demo
  profiles:
    active:
    - dev

app:
  name: '@project.name@'
  version: 'v@project.version@'

server:  ssl:    enabled: true
    key-cert-chain-file: ssl/crt.pem
    key-file: ssl/key.pem  http:
    #address: 0.0.0.0
    port: 12001

myboot:
  http:
    router:
      auto-init: true

##############################
# WeChat
wechat:
  global:
    appid: appid
    secret: secret
    mchid: mchid
    mch-secret: mch-secret

##############################
# MyBatis properties
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    local-cache-scope: statement
